// GIFTS
export const GIFTS_ARE_LOADING = 'GIFTS_ARE_LOADING';
export const GIFTS_FETCH_SUCCESS = 'GIFTS_FETCH_SUCCESS';
export const GIFTS_FETCH_FAILURE = 'GIFTS_FETCH_FAILURE';
export const ADD_GIFT = 'ADD_GIFT';
export const REMOVE_GIFT = 'REMOVE_GIFT';
export const SEARCH_GIFT = 'SEARCH_GIFT';

// USERS
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const CHECK_USERNAME_VALID = 'CHECK_USERNAME_VALID';
export const USERNAME_VALID_SUCCESS = 'USERNAME_VALID_SUCCESS';
export const USERNAME_VALID_FAILURE = 'USERNAME_VALID_FAILURE';
export const REMOVE_USER = 'REMOVE_USER';
export const BEFRIEND_USER = 'BEFRIEND_USER';
export const SEARCH_USERS = 'SEARCH_USERS';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAILURE = 'SEARCH_USERS_FAILURE';
